function Info = get_ctrl_info()
% -------------------------------------------------------------------
%  Generated by MATLAB on 30-Jul-2018 16:43:25
%  MATLAB version: 9.3.0.713579 (R2017b)
% -------------------------------------------------------------------
                                        

Info = struct;
Info.members = struct;
Info.members.v = struct;
Info.members.v.range = 1;
Info.members.v.size = [1 1];
Info.numel = 1;


end