function [dX,Debug] = get_symgen_step_loud_speaker_identification(X,v,n,p)
%GET_SYMGEN_STEP_LOUD_SPEAKER_IDENTIFICATION
%    [DX,DEBUG] = GET_SYMGEN_STEP_LOUD_SPEAKER_IDENTIFICATION(IN1,V,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    28-Jul-2018 13:50:27

Bl = p(3);
K_m = p(2);
M_m = p(4);
R_e = p(1);
R_m = X(3);
xd = X(1);
xd_dot = X(2);
dX = [xd_dot;
-(K_m.*xd+R_m.*xd_dot-(Bl.*(v-Bl.*xd_dot))./R_e)./M_m;
0.0];
if nargout > 1
    Debug = zeros(0,0);
end
