function [dX,Debug] = get_symgen_step_loud_speaker_simple(X,v,n,p)
%GET_SYMGEN_STEP_LOUD_SPEAKER_SIMPLE
%    [DX,DEBUG] = GET_SYMGEN_STEP_LOUD_SPEAKER_SIMPLE(IN1,V,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    27-Jul-2018 21:44:37

Bl = p(4);
K_m = p(3);
M_m = p(5);
R_e = p(1);
R_m = p(2);
xd = X(1);
xd_dot = X(2);
dX = [xd_dot;
-(K_m.*xd+R_m.*xd_dot-(Bl.*(v-Bl.*xd_dot))./R_e)./M_m];
if nargout > 1
    Debug = zeros(0,0);
end
