function [dX,Debug] = get_symgen_step_loud_speaker_identification_full(X,v,n,p)
%GET_SYMGEN_STEP_LOUD_SPEAKER_IDENTIFICATION_FULL
%    [DX,DEBUG] = GET_SYMGEN_STEP_LOUD_SPEAKER_IDENTIFICATION_FULL(IN1,V,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    30-Jul-2018 16:43:25

Bl = p(1);
K_m = X(4);
M_m = p(2);
R_e = X(5);
R_m = X(3);
xd = X(1);
xd_dot = X(2);
dX = [xd_dot;
-(K_m.*xd+R_m.*xd_dot-(Bl.*(v-Bl.*xd_dot))./R_e)./M_m;
0.0;
0.0;
0.0];
if nargout > 1
    Debug = zeros(0,0);
end
