function Info = get_dstate_info()
% -------------------------------------------------------------------
%  Generated by MATLAB on 29-Jul-2018 00:02:51
%  MATLAB version: 9.3.0.713579 (R2017b)
% -------------------------------------------------------------------
                                          

Info = struct;
Info.members = struct;
Info.members.xd_dot = struct;
Info.members.xd_dot.range = 1;
Info.members.xd_dot.size = [1 1];
Info.members.xd_dot_dot = struct;
Info.members.xd_dot_dot.range = 2;
Info.members.xd_dot_dot.size = [1 1];
Info.members.R_m_dot = struct;
Info.members.R_m_dot.range = 3;
Info.members.R_m_dot.size = [1 1];
Info.members.K_m_dot = struct;
Info.members.K_m_dot.range = 4;
Info.members.K_m_dot.size = [1 1];
Info.members.R_e_dot = struct;
Info.members.R_e_dot.range = 5;
Info.members.R_e_dot.size = [1 1];
Info.numel = 5;


end