function Info = get_parameters_info()
% -------------------------------------------------------------------
%  Generated by MATLAB on 29-Jul-2018 00:02:50
%  MATLAB version: 9.3.0.713579 (R2017b)
% -------------------------------------------------------------------
                                              

Info = struct;
Info.members = struct;
Info.members.Bl = struct;
Info.members.Bl.range = 1;
Info.members.Bl.size = [1 1];
Info.members.M_m = struct;
Info.members.M_m.range = 2;
Info.members.M_m.size = [1 1];
Info.numel = 2;


end