function Info = get_state_info()
% -------------------------------------------------------------------
%  Generated by MATLAB on 30-Jul-2018 16:43:25
%  MATLAB version: 9.3.0.713579 (R2017b)
% -------------------------------------------------------------------
                                         

Info = struct;
Info.members = struct;
Info.members.xd = struct;
Info.members.xd.range = 1;
Info.members.xd.size = [1 1];
Info.members.xd_dot = struct;
Info.members.xd_dot.range = 2;
Info.members.xd_dot.size = [1 1];
Info.members.R_m = struct;
Info.members.R_m.range = 3;
Info.members.R_m.size = [1 1];
Info.members.K_m = struct;
Info.members.K_m.range = 4;
Info.members.K_m.size = [1 1];
Info.members.R_e = struct;
Info.members.R_e.range = 5;
Info.members.R_e.size = [1 1];
Info.numel = 5;


end